version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

jobs:
  unit_test:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --collectCoverage=true
          name: Run Jest tests
      - store_artifacts:
          path: coverage
  lint:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run Jest tests
  happy_hour:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn hydrate
          name: Make sure you drink some water!
      - run:
          command: yarn time-to-drink
          name: Where are we going?
      - store_artifacts:
          path: ./videos
      - store_artifacts:
          path: ./test-results

workflows:
  on_commit:
    jobs:
      - lint
      - unit_test
      - request_happy_hour:
          type: approval
          requires:
            - lint
            - unit_test
      - happy_hour:
          requires:
            - request_happy_hour
  nightly:
    triggers:
      - schedule:
          # Run at 3:30pm on Tuesdays
          cron: "30 22 * * 2"
          filters:
            branches:
              only:
                - main
    jobs:
      -   happy_hour
